### ISSUE TITLE
视频上下白边问题

### ISSUE THREAD

**Issue by yuxuhao** [yangfeng1994/video-list-player#1]
老铁 item视频上下白边是不是很不好看 是什么原因啊，想用你这个项目。

**Comment by yangfeng1994** [comment]
视频尺寸的问题。

**Comment by yangfeng1994** [comment]
如果使用exoplayer 可以修改属性为 
simpleExoPlayer.setVideoScalingMode(C.VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING)
playerView.resizeMode = AspectRatioFrameLayout.RESIZE_MODE_FILL
